bloxbean/yaci-store

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/AddressUtxo.java, components/stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/AssetsStoreConfiguration.java, components/stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/domain/TxAssetEvent.java, components/stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/processor/AssetMintBurnProcessor.java, components/stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/storage/AssetStorageImpl.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/ScriptStoreConfiguration.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/domain/DatumEvent.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/domain/TxScriptEvent.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/processor/OutputDatumProcessor.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/processor/ScriptRedeemerDatumProcessor.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/storage/impl/jpa/DatumStorageImpl.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/storage/impl/jpa/ScriptStorageImpl.java, components/stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/storage/impl/jpa/TxScriptStorageImpl.java, components/stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/TransactionStoreConfiguration.java, components/stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/TransactionProcessor.java, components/stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/TransactionStorageImpl.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/UtxoStoreConfiguration.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/domain/AddressUtxoEvent.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoProcessor.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/jpa/InvalidTransactionStorageImpl.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/jpa/UtxoStorageImpl.java, components/stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/jpa/model/AddressUtxoEntity.java, components/stores/utxo/src/main/resources/db/migration/h2/V0_200_1__init.sql, components/stores/utxo/src/main/resources/db/migration/mysql/V0_200_1__init.sql, components/stores/utxo/src/main/resources/db/migration/postgresql/V0_200_1__init.sql, components/stores/utxo/src/test/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoProcessorTest.java
- Removed @Component and added @ConditionalOnBean annotation to enable custom storage impl for assets, script, transaction, utxo stores
- Published derived events like AddressUtxoEvent, MetadataEvent etc which can be consumed by external stores
- New lovelace_amont in AddressUtxo table
=> Custom storage fix

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/configuration/GenesisConfig.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/EraService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/StartService.java, components/core/src/test/java/com/bloxbean/cardano/yaci/store/core/service/EraServiceTest.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/EventMetadata.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/GenesisBlockEvent.java, components/stores/blocks/src/main/java/com/bloxbean/cardano/yaci/store/blocks/processor/BlockProcessor.java, components/stores/blocks/src/main/java/com/bloxbean/cardano/yaci/store/blocks/processor/ByronBlockProcessor.java, config/application.properties, gradle.properties, gradle/libs.versions.toml
- Fixed Genesis epoch era (for local devnet)
- Fixed incorrect blocktime
=> Fix genesis epoch

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/StoreProperties.java, components/submit/build.gradle, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/OgmiosTxSubmissionController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/TxSubmitController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/TxUtilController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/service/OgmiosService.java, gradle/libs.versions.toml, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
- Added support for Ogmios. Another option for tx submission and tx cost evaluation
=> feat: Ogmios support to submit and evaluate transaction

stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/controller/MetadataController.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/dto/MetadataDtoMapper.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/dto/MetadataLabelDto.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/service/MetadataService.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/storage/TxMetadataStorage.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/storage/impl/jpa/TxMetadataStorageImpl.java, stores/metadata/src/main/java/com/bloxbean/cardano/yaci/store/metadata/storage/impl/jpa/repository/TxMetadataLabelRepository.java, test-scripts/query.http
=> feat: Add get metadata by label method and endpoint

stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/controller/AssetController.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/domain/TxAsset.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/processor/AssetMintBurnProcessor.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/service/AssetService.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/storage/AssetStorage.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/storage/AssetStorageImpl.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/storage/model/TxAssetEntity.java, stores/assets/src/main/java/com/bloxbean/cardano/yaci/store/assets/storage/repository/TxAssetRepository.java, stores/assets/src/main/resources/db/migration/h2/V0_700_1__init.sql, stores/assets/src/main/resources/db/migration/h2/V0_700_2__indexes.sql, stores/assets/src/main/resources/db/migration/mysql/V0_700_1__init.sql, stores/assets/src/main/resources/db/migration/mysql/V0_700_2__indexes.sql, stores/assets/src/main/resources/db/migration/postgresql/V0_700_1__init.sql, stores/assets/src/main/resources/db/migration/postgresql/V0_700_2__indexes.sql, test-scripts/query.http
New storage methods and endpoints
```
List<TxAsset> findByFingerprint(String fingerprint, int page, int count);
List<TxAsset> findByPolicy(String policyId, int page, int count);
List<TxAsset> findByUnit(String unit, int page, int count);
Optional<Integer> getSupplyByFingerprint(String fingerprint);
Optional<Integer> getSupplyByUnit(String unit);
Optional<Integer> getSupplyByPolicy(String policyId);
```
=> feat(assets): Added fingerprint. Finders for unit, policy, fingerprint

components/common/build.gradle, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFinder.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/CursorService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/StartService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/api/CursorStorage.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/CursorRepository.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/CursorStorageImpl.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/BlockEvent.java, gradle/libs.versions.toml, starters/spring-boot-starter/build.gradle, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, stores/blocks/src/main/java/com/bloxbean/cardano/yaci/store/blocks/processor/BlockProcessor.java, stores/blocks/src/main/java/com/bloxbean/cardano/yaci/store/blocks/storage/api/BlockStorage.java, stores/blocks/src/main/java/com/bloxbean/cardano/yaci/store/blocks/storage/impl/jpa/BlockStorageImpl.java, stores/build.gradle
- Fix: Check valid / invalid cursor during restart
=> feat: Check valid/invalid cursor blocks during restart

stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/controller/ScriptController.java, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/dto/TxRedeemerDto.java, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/service/ScriptService.java, test-scripts/query.http
New endpoint
- /txs/<tx_hash>/redeemers
=> feat: #82 Api to get redeemers for a transaction

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/AddressBalance.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/StakeAddressBalance.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/jpa/model/AddressBalanceEntity.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/jpa/model/StakeAddressBalanceEntity.java, aggregates/account/src/main/resources/db/store/h2/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/mysql/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/postgresql/V0_900_1__init.sql
- Remove deletion of record during server statup to avoid balance not found error
- Added blocktime to both address balance and stake address balance table
=> fix: Fix account module to avoid error. Added blockTime

applications/all/build.gradle, applications/gateway/build.gradle, applications/utxo-indexer/build.gradle, build.gradle, config/application.properties, gradle.properties, gradle/libs.versions.toml
- To fix incorrect Tx hash issue for some mainnet transactions
- Sanchonet support
=> Update Yaci and CCL version 

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/controller/AddressAssetController.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/dto/AddressAssetBalanceDto.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/service/AddressAssetService.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AccountBalanceStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/jpa/AccountBalanceStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/jpa/repository/AddressBalanceRepository.java, test-scripts/query.http
#103 
- New endpoint
/assets/{unit}/addresses
=> fix: #103 added a new method to return addreses for an asset.

applications/all/sql/create-index.sql, applications/all/sql/drop-index.sql, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/TransactionStoreConfiguration.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/controller/TransactionController.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/domain/TxWitnessType.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/domain/TxnWitness.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/ByronTransactionProcessor.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/TransactionProcessor.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/TransactionRollbackProcessor.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/service/TransactionService.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/api/TransactionWitnessStorage.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/TransactionWitnessStorageImpl.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/mapper/TxnMapper.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/model/TxnWitnessEntity.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/model/TxnWitnessId.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/repository/TxnWitnessRepository.java, stores/transaction/src/main/resources/db/store/h2/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/h2/V0_300_2__indexes.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_2__indexes.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_2__indexes.sql, test-scripts/query.http
- Store transaction witnesses
- Add endpoint to return witnesses by tx hash
=> feat: #106 Initial impl for transaction witness support

applications/all/src/main/java/com/bloxbean/cardano/yaci/store/app/DBIndexService.java, applications/all/src/main/resources/sql/create-index.sql, applications/all/src/main/resources/sql/drop-index.sql, applications/all/src/main/resources/sql/mysql/create-index.sql, applications/all/src/main/resources/sql/mysql/drop-index.sql, config/application.properties, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/model/TxnWitnessEntity.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/jpa/model/TxnWitnessId.java, stores/transaction/src/main/resources/db/store/h2/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_1__init.sql, stores/utxo/src/main/resources/db/store/h2/V0_200_1__init.sql
- Auto manage index drop and creation during sync process
#118
=> Drop optional indexes during sync

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/AccountApiConfiguration.java, config/application.properties, starters/live-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/live/LiveStoreProperties.java, starters/mir-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/mir/MIRStoreAutoConfiguration.java, starters/mir-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/mir/MIRStoreProperties.java, starters/staking-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/staking/StakingStoreAutoConfiguration.java, starters/staking-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/staking/StakingStoreProperties.java, stores-api/assets-api/src/main/java/com/bloxbean/cardano/yaci/store/api/assets/AssetsApiConfiguration.java, stores-api/blocks-api/src/main/java/com/bloxbean/cardano/yaci/store/api/blocks/BlocksApiConfiguration.java, stores-api/epoch-api/src/main/java/com/bloxbean/cardano/yaci/store/api/epoch/EpochApiConfiguration.java, stores-api/metadata-api/src/main/java/com/bloxbean/cardano/yaci/store/api/metadata/MetadataApiConfiguration.java, stores-api/mir-api/src/main/java/com/bloxbean/cardano/yaci/store/api/mir/MIRApiConfiguration.java, stores-api/script-api/src/main/java/com/bloxbean/cardano/yaci/store/api/script/ScriptApiConfiguration.java, stores-api/staking-api/src/main/java/com/bloxbean/cardano/yaci/store/api/staking/StakingApiConfiguration.java, stores-api/transaction-api/src/main/java/com/bloxbean/cardano/yaci/store/api/transaction/TransactionApiConfiguration.java, stores-api/utxo-api/src/main/java/com/bloxbean/cardano/yaci/store/api/utxo/UtxoApiConfiguration.java, stores/live/src/main/java/com/bloxbean/cardano/yaci/store/live/LiveStoreConfiguration.java, stores/mir/src/main/java/com/bloxbean/cardano/yaci/store/mir/MIRStoreConfiguration.java, stores/staking/src/main/java/com/bloxbean/cardano/yaci/store/staking/StakingStoreConfiguration.java
=> fix: #138 Disable api module when store is already disabled.

.gitignore, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceRollbackProcessor.java, applications/aggregation-app/build.gradle, applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/ApplicationStartupListener.java, applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/config/EmbeddedDBConfig.java, applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/storage/EmbeddedUtxoStorage.java, applications/aggregation-app/src/main/resources/application.yml, applications/aggregation-app/src/main/resources/sql/clean-db.sql, components/rocksdb/build.gradle, components/rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/rocksdb/KVRepository.java, components/rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/rocksdb/RocksDBConfig.java, components/rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/rocksdb/RocksDBProperties.java, components/rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/rocksdb/RocksDBRepository.java, config/application-aggr.properties, gradle/libs.versions.toml, settings.gradle
- New storage adapter for rocksdb
- Integrate rocksdb to store utxos in aggregation module, so that balance calculation can run independently
=> Account balance calculation fix + rocksdb integration for utxo store in aggregation app

stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/helper/RedeemerDatumMatcher.java
=> fix: #148 sort inputs before getting input for redeemer

config/application.properties, stores-api/governance-api/src/main/java/com/bloxbean/cardano/yaci/store/api/governance/controller/GovActionProposalController.java, stores-api/governance-api/src/main/java/com/bloxbean/cardano/yaci/store/api/governance/controller/VotingProcedureController.java, stores-api/governance-api/src/main/java/com/bloxbean/cardano/yaci/store/api/governance/service/GovActionProposalService.java, stores-api/governance-api/src/main/java/com/bloxbean/cardano/yaci/store/api/governance/service/VotingProcedureService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/GovActionProposalStorageReader.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/VotingProcedureStorageReader.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/GovActionProposalStorageReaderImpl.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/VotingProcedureStorageReaderImpl.java, test-scripts/query.http
Changes:
1. New endpoints to return all proposals and voting procedures by page
2. Update the resource names to plural
=> New endpoints for governance store

stores-api/governance-api/src/main/java/com/bloxbean/cardano/yaci/store/api/governance/dto/VotingProcedureDtoMapper.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/DelegationVote.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/DRepRegistrationProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/DelegationVoteProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/VotingProcedureProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/DelegationVoteEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/VotingProcedureEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/VotingProcedureId.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/repository/VotingProcedureRepository.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/util/DRepId.java, stores/governance/src/main/resources/db/store/h2/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_1__init.sql, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/DelegationVoteProcessorTest.java
=> Update governance store and governance-api

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/domain/HealthStatus.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/HealthService.java, gradle/libs.versions.toml
=> feat: add health service to get health status

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/EraService.java, components/core/src/test/java/com/bloxbean/cardano/yaci/store/core/configuration/EpochConfigTest.java, components/core/src/test/java/com/bloxbean/cardano/yaci/store/core/service/EraServiceTest.java
=> Fix incorrect block time and epoch slotno error in preview

applications/all/src/main/resources/sql/create-index.sql, applications/all/src/main/resources/sql/drop-index.sql, applications/all/src/main/resources/sql/mysql/create-index.sql, applications/all/src/main/resources/sql/mysql/drop-index.sql, stores-api/transaction-api/src/main/java/com/bloxbean/cardano/yaci/store/api/transaction/controller/AccountWithdrawalController.java, stores-api/transaction-api/src/main/java/com/bloxbean/cardano/yaci/store/api/transaction/controller/TxWithdrawalController.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/TransactionStoreConfiguration.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/domain/Withdrawal.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/domain/WithdrawalEvent.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/WithdrawalProcessor.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/WithdrawalStorage.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/WithdrawalStorageReader.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/WithdrawalStorageImpl.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/WithdrawalStorageReaderImpl.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/mapper/TxnMapper.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/model/WithdrawalEntity.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/model/WithdrawalId.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/repository/WithdrawalRepository.java, stores/transaction/src/main/resources/db/store/h2/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/h2/V0_300_2__indexes.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_2__indexes.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_2__indexes.sql, stores/transaction/src/test/java/com/bloxbean/cardano/yaci/store/transaction/processor/WithdrawalProcessorTest.java, stores/transaction/src/test/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/WithdrawalStorageImplTest.java, stores/transaction/src/test/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/WithdrawalStorageReaderImplTest.java, test-scripts/query.http
#207 
- Withdrawal data added to transaction store
=> feat: #207 Withdrawal implementation

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/AddressTxAmount.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressTxAmountProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/GensisBlockAddressTxAmtProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AddressTxAmountStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressTxAmountStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/mapper/AggrMapper.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/mapper/AggrMapperDecorator.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/model/AddressTxAmountEntity.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/model/AddressTxAmountId.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/repository/AddressTxAmountRepository.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/util/AddressUtil.java, aggregates/account/src/main/resources/db/store/h2/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/mysql/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/postgresql/V0_900_1__init.sql
- Move address_tx_amount to yaci store as it can also be used to derive address_balance snapshot in future.
=> feat: Store amount for address at tx level

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/Address.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/AddressBalance.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/StakeAddressBalance.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressTxAmountProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/GensisBlockAddressTxAmtProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AddressStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AccountBalanceStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressTxAmountStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/model/AddressBalanceEntity.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/model/StakeAddressBalanceEntity.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/controller/AccountController.java, aggregates/account/src/main/resources/db/store/h2/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/mysql/V0_900_1__init.sql, aggregates/account/src/main/resources/db/store/postgresql/V0_900_1__init.sql, applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/DBIndexService.java, applications/aggregation-app/src/main/resources/sql/create-index.sql, applications/aggregation-app/src/main/resources/sql/drop-index.sql, applications/aggregation-app/src/main/resources/sql/mysql/create-index.sql, applications/aggregation-app/src/main/resources/sql/mysql/drop-index.sql, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/UtxoKey.java
- Remove additional columns from address_balance and stake_address_balance table
- Update create and drop index files
- As address balance processing is an optional step, add new address to address table during AddressTxAmount processing.
=> Remove additional columns from balance tables 

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreProperties.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressTxAmountProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AddressStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressStorageImpl.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressTxAmountStorageImpl.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfigProperties.java
- Address Tx Amount with 0 quantity
- Default batch size for write thread has been changed to 1000 from 6000
- Log level change
- Set to ConcurrentHashMap in AddressProcessor
=> Include address tx amount with 0 quantity

components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/HealthService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/publisher/ByronBlockEventPublisher.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/publisher/ShelleyBlockEventPublisher.java
- Added timeout to block / event processing threads
- Move HealthService to admin module
=> Added timeout to processing threads

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/config/UtxoAccountBatchConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/AccountConfigUpdateTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/AccountJobConstants.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/CreateStakeAddressTableTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/DropStakeAddressTableTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/utxo/AddressUtxoAggregationTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/utxo/StakeAddressUtxoAggregationTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/service/BalanceSnapshotService.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/util/ConfigStatus.java, components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/AutoRecoveryStartService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/StartService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/publisher/ByronBlockEventPublisher.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/publisher/ShelleyBlockEventPublisher.java
- Added batchMode property (utxo or tx-amount aggregation)
- Initial implementation of AutoRecoveryService to restart Sync service if required.
=> chore: Calculate balance by aggregating utxos

aggregates/account/build.gradle, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreProperties.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/CreateStakeAddressTableTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/DropStakeAddressTableTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/utxo/AddressUtxoAggregationTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/service/BalanceSnapshotService.java, applications/all/src/main/java/com/bloxbean/cardano/yaci/store/app/YaciStoreApplication.java, applications/all/src/main/resources/application.yml, applications/all/src/main/resources/sql/create-index.sql, applications/all/src/main/resources/sql/drop-index.sql, applications/all/src/main/resources/sql/mysql/create-index.sql, applications/all/src/main/resources/sql/mysql/drop-index.sql, applications/utxo-indexer/build.gradle, applications/utxo-indexer/src/main/java/com/bloxbean/cardano/yaci/store/app/utxo/DBIndexService.java, applications/utxo-indexer/src/main/resources/sql/create-index.sql, applications/utxo-indexer/src/main/resources/sql/drop-index.sql, applications/utxo-indexer/src/main/resources/sql/mysql/create-index.sql, applications/utxo-indexer/src/main/resources/sql/mysql/drop-index.sql, components/admin/build.gradle, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfigProperties.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfiguration.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageImpl.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/mapper/UtxoMapperDecorator.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/model/AmtEntity.java, stores/utxo/src/main/resources/db/store/h2/V0_200_1__init.sql, stores/utxo/src/main/resources/db/store/mysql/V0_200_1__init.sql, stores/utxo/src/main/resources/db/store/postgresql/V0_200_1__init.sql
- New column owner_addr in utxo_amount
- Update auto db index management scripts
- Added a check to verify if there are any records in the balance tables before starting the UTXO based balance calculation. UTXO based balance calculations can only be performed when the address_balance and stake_address_balance tables are empty.
=> Add owner_addr column to utxo_amount to optimize balance snapshot query

components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/HealthService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/HealthStatus.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java
=> chore: (HealthService) Add last received block time

applications/all/src/main/resources/sql/create-index.sql, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/Utxo.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/OgmiosTxSubmissionController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/TxLocalSubmitController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/TxSubmitController.java, components/submit/src/main/java/com/bloxbean/cardano/yaci/store/submit/controller/TxUtilController.java
- Fixed Tx Evaluation endpoint which uses Ogmios endpoint to evaluate tx
- Added additional initialization condition for OgmiosTxSubmissionController
- Update "quantity" field in Utxo.amount to String for API's json output. This is to avoid rounding issue in Javascript.
=> Tx submission and Tx evaluation api fixes

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/service/AddressBalanceSnapshotService.java, components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/api/AdminController.java
- If negative balance, calculate current balance from address_tx_amount
- Added admin endpoint to calculate current address balance for list of addresses
=> chore: Recover from negative balance during address balance calculation

stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/CommitteeMember.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeMemberProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/CommitteeMemberEntity.java, stores/governance/src/main/resources/db/store/h2/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_1__init.sql
Add a start_epoch column to represent the epoch in which the committee member becomes active
=> chore: add start_epoch to committee_member table

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/CreateStakeAddressTableTasklet.java
=> fix: #283 remove index creation for utxo_amount table

stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessor.java, stores/epoch/src/test/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessorTest.java
- Get PP with target epoch as previous epoch, so that it can be applied in the current epoch
=> chore: #307 Get PP with target epoch as previous epoch

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/AccountApiConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/controller/AccountController.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/service/AccountService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/api/EraStorage.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/EraRepository.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/EraStorageImpl.java
=> Local query reward balance failure due to incorrect era & AccountController's path variable fix

stores/governance/src/main/resources/db/store/h2/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_1__init.sql
#319 
- Fix index issue: there are two indexes define for same column 'slot' (drep_registration)
- Add "drop table if exists ..."
- Format SQL
=> [governance] Update migration script

gradle/libs.versions.toml, starters/epoch-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/epoch/EpochStoreProperties.java, starters/governance-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/governance/GovernanceStoreProperties.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/LocalEpochParamsScheduler.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/service/LocalEpochParamService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/LocalGovernanceStoreConfiguration.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/LocalDRepDistr.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/LocalDRepDistrProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/LocalGovActionStateProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/service/LocalDRepDistrService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/service/LocalGovStateService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/LocalDRepDistrStorage.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/LocalDRepDistrStorageImpl.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/mapper/LocalDRepDistrMapper.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/LocalDRepDistrEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/LocalDRepDistrId.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/repository/LocalDRepDistrRepository.java, stores/governance/src/main/resources/db/store/h2/V0_1100_2__add-gov-state-tables.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_2__add-gov-state-tables.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_2__add-gov-state-tables.sql
=> feat: handle local drep stake distribution and introduce new properties

config/application.properties, gradle.properties
- Update version to rc6
- Update mainnet host in application.properties
- Remove additional submit.url.host from properties file
=> Update version and adjust Cardano mainnet host URL

applications/admin/build.gradle, applications/aggregation-app/build.gradle, applications/all/build.gradle, applications/gateway/build.gradle, applications/utxo-indexer/build.gradle, build.gradle, components/common/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Replaced hardcoded Spring Boot and Dependency Management versions with variables in multiple build.gradle files. Added new properties to gradle.properties and updated the Gradle wrapper version.
#375
=> Update Spring Boot versions and add dependency properties

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/Amt.java
=> fix: #399 Add serializer to convert amount from BigIn to String

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/client/ProposalStateClientImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalRefundProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/TreasuryWithdrawalProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/mapper/ProposalMapper.java, aggregates/governance-aggr/src/test/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalRefundProcessorTest.java, aggregates/governance-aggr/src/test/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/TreasuryWithdrawalProcessorTest.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/GovActionProposal.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, stores/epoch/build.gradle, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessor.java, stores/epoch/src/test/java/com/bloxbean/cardano/yaci/store/epoch/SpringBootTestApplication.java, stores/epoch/src/test/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessorTest.java
- Update domain class GovActionProposal in common module and the related code
- Update Param Protocol after the PP change action's enacted
=> Update Param Protocol after the PP change action's enacted

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/genesis/ConwayGenesis.java, components/common/src/test/java/com/bloxbean/carano/yaci/store/common/genesis/ConwayGenesisTest.java, stores/governance/build.gradle, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/Committee.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/CommitteeDeRegistration.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/CommitteeMember.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/domain/CommitteeRegistration.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeMemberProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeRegistrationProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/ConstitutionProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/CommitteeMemberStorageImpl.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/CommitteeDeRegistrationEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/CommitteeEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/CommitteeMemberEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/CommitteeRegistrationEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/repository/CommitteeMemberRepository.java, stores/governance/src/main/resources/db/store/h2/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_1__init.sql, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/SpringBootTestApplication.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeMemberProcessorTest.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeProcessorTest.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeRegistrationProcessorTest.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/ConstitutionProcessorTest.java
- Update the committee and constitution after the corresponding governance actions are enacted, write unit tests
- Add 'epoch' column to 'committee_member' table
- Update query for getting active committee members
- Add tx_index to table 'committee_registration/deregistration'
=> update the committee and constitution after the corresponding governance actions are enacted and add  column 'epoch' to table'committee_member' 

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/configuration/DevkitGenesisFetcher.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/configuration/GenesisConfig.java, e2e-tests/README.md, e2e-tests/build.gradle, e2e-tests/src/main/java/com/bloxbean/cardano/yaci/store/test/e2e/E2ETestApplication.java, e2e-tests/src/test/java/com/bloxbean/cardano/yaci/store/test/e2e/common/BaseE2ETest.java, e2e-tests/src/test/java/com/bloxbean/cardano/yaci/store/test/e2e/common/TransactionHelper.java, e2e-tests/src/test/java/com/bloxbean/cardano/yaci/store/test/e2e/gov/InfoProposalLifeCycleIT.java, e2e-tests/src/test/resources/application.properties, gradle/libs.versions.toml, publish-common.gradle, settings.gradle, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
=> E2E test module setup + Download genesis files for Devkit automatically

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/AdaPotJobManager.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/domain/AdaPotJob.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/AdaPotJobStorage.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/impl/AdaPotJobEntity.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/impl/AdaPotJobRepository.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/impl/AdaPotJobStorageImpl.java, aggregates/adapot/src/main/resources/db/store/h2/V0_1300_1__init.sql, aggregates/adapot/src/main/resources/db/store/mysql/V0_1300_1__init.sql, aggregates/adapot/src/main/resources/db/store/postgresql/V0_1300_1__init.sql, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java
- Removed catching exception and reformat code in the ProposalStatusProcessor
- Added era checking before gov action status calc and drep dist calc
- Added drep distr query time to adapot_jobs table
=>  Fix adapot job status tracking and add drep distribution time (#473, #463)

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/domain/DRep.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/DRepStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/GovActionProposalStatusStorage.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/GovActionProposalStatusStorageImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/DRepEntity.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/repository/GovActionProposalStatusRepository.java, aggregates/governance-aggr/src/main/resources/db/store/h2/V0_1400_1__init.sql, aggregates/governance-aggr/src/main/resources/db/store/mysql/V0_1400_1__init.sql, aggregates/governance-aggr/src/main/resources/db/store/postgresql/V0_1400_1__init.sql, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessor.java
#486 
- Add column 'registration_slot' to table 'drep_dist' and adjust the drep distr query
- Update protocol param after the hard fork init action is enacted
=> Add column 'registration_slot' to table 'drep_dist' and adjust the drep distr query

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/GovernanceAggrConfiguration.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/client/ProposalStateClientImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/domain/DRepExpiry.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/DRepExpiryProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/DRepStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/VotingAggrService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/DRepExpiryStorage.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/DRepStorage.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/GovActionProposalStatusStorage.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepExpiryStorageImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepStorageImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/GovActionProposalStatusStorageImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/mapper/DRepExpiryMapper.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/DRepExpiryEntity.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/DRepExpiryId.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/DRepStatus.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/repository/DRepExpiryRepository.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/repository/GovActionProposalStatusRepository.java, aggregates/governance-aggr/src/main/resources/META-INF/native-image/yaci-store-gov-aggr/reflect-config.json, aggregates/governance-aggr/src/main/resources/db/store/h2/V0_1400_1__init.sql, aggregates/governance-aggr/src/main/resources/db/store/mysql/V0_1400_1__init.sql, aggregates/governance-aggr/src/main/resources/db/store/postgresql/V0_1400_1__init.sql, components/client/src/main/java/com/bloxbean/cardano/yaci/store/client/governance/DummyProposalStateClientImpl.java, components/client/src/main/java/com/bloxbean/cardano/yaci/store/client/governance/ProposalStateClient.java, components/dbutils/src/main/java/com/bloxbean/cardano/yaci/store/dbutils/index/service/RollbackService.java, components/dbutils/src/main/resources/rollback.yml, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/repository/VotingProcedureRepository.java
=> [Governance] Implement DRep expiry handling

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/EraService.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/LocalEpochParamsScheduler.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/service/LocalEpochParamService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/local/LocalGovActionStateProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/service/LocalDRepDistrService.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/service/LocalGovStateService.java
- Add synchronized to fix connection issue during local query
- Add Conway era checking during fetching data with local queries
=> Add synchronized to fix connection issue during local query

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/client/ProposalStateClientImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/mapper/ProposalMapper.java
- Update proposal status calculation logic, refactor code
- Create temp table ss_earned_reward_rest during drep distr calculation.
- Align epoch value with snapshot epoch when inserting drep distr records
=> Fix missing ada issue in auto-abstain drep distribution

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/AdaPotJobManager.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/AdaPotJobProcessor.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/domain/AdaPotJob.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/impl/AdaPotJobEntity.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/job/storage/impl/AdaPotJobStorageImpl.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/processor/AdaPotProcessor.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/AdaPotService.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/EpochRewardCalculationService.java, aggregates/adapot/src/main/resources/db/store/h2/V0_1300_1__init.sql, aggregates/adapot/src/main/resources/db/store/mysql/V0_1300_1__init.sql, aggregates/adapot/src/main/resources/db/store/postgresql/V0_1300_1__init.sql, aggregates/governance-aggr/src/test/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalRefundProcessorTest.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/internal/PreAdaPotJobProcessingEvent.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/EpochParamProcessor.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/service/ProtocolParamService.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/EpochParamStorageImpl.java
- Remove Cache annotation from ProtocolParamService.getProtocolParam
- Add block number to adapot job
- Extract job processing code from AdaPotJobManager to AdaPotJobProcessor
=> Fix: Epoch Param not found error

e2e-tests/src/main/java/com/bloxbean/cardano/yaci/store/test/e2e/DrepDataComparator.java
=> chore: Comparator utility to compare drep dist between db sync and yaci store

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/AdaPotConfiguration.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/storage/AdaPotStorageReader.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/storage/impl/AdaPotStorageReaderImpl.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/storage/impl/repository/AdaPotRepository.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/api/adapot/controller/AdaPotController.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/api/adapot/service/AdaPotApiService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java, e2e-tests/src/main/java/com/bloxbean/cardano/yaci/store/test/e2e/DrepDataComparator.java
- Fix snaphsot epoch in Drep dist service
- Use currentEpoch to invoke takeDrepSnapshot in ProposalStatusService
- New adapot api in AdaPotController 
- Display drep id in DRepComparator
=> fix: Handle snapshot epoch properly in drep distr, AdaPot api to get adapots

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/EpochRewardCalculationService.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/PoolStateService.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/api/adapot/controller/EpochStakeController.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/api/adapot/dto/AddressPoolRewardDto.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/api/adapot/service/RewardApiService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/util/PoolUtil.java, stores-api/staking-api/src/main/java/com/bloxbean/cardano/yaci/store/api/staking/controller/PoolController.java, stores-api/staking-api/src/main/java/com/bloxbean/cardano/yaci/store/api/staking/dto/PoolDetailsDto.java
- Fix Pool Controller endpoints
- Move PoolUtil to common module
=> fix: Pool Controller endpoints path parameters

applications/admin-cli/src/main/java/com/bloxbean/cardano/yaci/store/admin/cli/db/DBCommands.java, components/dbutils/src/main/java/com/bloxbean/cardano/yaci/store/dbutils/index/model/RollbackContext.java, components/dbutils/src/main/java/com/bloxbean/cardano/yaci/store/dbutils/index/service/RollbackService.java, components/dbutils/src/main/resources/rollback-ledger-state.yml
ex: rollback-ledger-state-data --epoch 167
=> Add command for ledger state data rollback

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/GovernanceAggrApiConfiguration.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/controller/DRepInfoController.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/controller/ProposalController.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/DRepDetailsDto.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/DRepStatus.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/ProposalDto.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/ProposalStatus.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/service/DRepApiService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/service/ProposalApiService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/GovernanceAggrConfiguration.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/DRepExpiryProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/DRepStorageReader.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/GovActionProposalStatusStorageReader.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepStorageReaderImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/GovActionProposalStatusStorageReaderImpl.java, config/application-ledger-state.properties, starters/governance-aggr-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/governanceaggr/GovernanceAggrStoreAutoConfiguration.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/GovActionProposalStorageReader.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/GovActionProposalStorageReaderImpl.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/repository/GovActionProposalRepository.java
=> Add endpoints for Proposal, DRep data

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/CursorStorageImpl.java, stores/staking/src/main/resources/META-INF/native-image/yaci-store-staking/reflect-config.json
To fix, no transaction error for native image + mysql
=> fix: Add Transactional annotation to update operations

stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeMemberProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeProcessor.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/processor/ConstitutionProcessor.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeMemberProcessorTest.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/CommitteeProcessorTest.java, stores/governance/src/test/java/com/bloxbean/cardano/yaci/store/governance/processor/ConstitutionProcessorTest.java
=> Update committee and constitution when handling PreAdaPotJobProcessingEvent

components/dbutils/src/main/resources/META-INF/native-image/yaci-store-dbutils/resource-config.json, docker/env, docker/postgres-compose.yml, docker/yaci-store-ledger-state.yml, docker/yaci-store-utxo-indexer.yml, docker/yaci-store.yml
- Added missing index yml files in native image's resource config
=> fix: Added missing index/rollback files for native image

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/ProposalDto.java
=> Return snake case in proposals endpoint

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/DRepDetailsDto.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepStorageReaderImpl.java
=> fix: Fix null fields in Dreps endpoint

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/controller/ProposalStatusDebugController.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/DRepDistStorageReader.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepDistStorageReaderImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/DRepDistId.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/repository/DRepDistRepository.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/util/DRepUtil.java, components/dbutils/src/main/java/com/bloxbean/cardano/yaci/store/dbutils/index/service/RollbackService.java
#544 
- Search drep distr by drepId instead of drepHash
- New debug controller which is only enabled for debug profile
=> Incorrect proposal status calculation in epoch 541 (mainnet) which causes missing proposal refund.

applications/admin-cli/src/main/java/com/bloxbean/cardano/yaci/store/admin/cli/db/DBCommands.java, components/dbutils/src/main/java/com/bloxbean/cardano/yaci/store/dbutils/index/service/RollbackService.java
=> Disable rollback ledger state data

Dockerfile, applications/ledger-state/src/main/java/com/bloxbean/cardano/yaci/store/ledgerstate/config/DefaultConfig.java, applications/ledger-state/src/main/resources/application.yml, docker/admin-cli-compose.yml, docker/admin-cli.sh, docker/application.properties, docker/postgres-compose-minimal.yml, docker/yaci-store-ledger-state-monolith.yml, docker/yaci-store-ledger-state.yml, docker/yaci-store-monolith.yml, docker/yaci-store-utxo-indexer-monolith.yml, docker/yaci-store-utxo-indexer.yml, docker/yaci-store.yml
- Remove DB settings from compose file. DB configurations are now done through application.properties or env file.
- Set default properties in ledger-state app's application.yml file
- Added new compose yml for admin-cli app
=> JDK 24 for runtime + Docker compose file changes to externalize DB settings

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/VotingAggrService.java, stores/governance/src/main/resources/db/store/h2/V0_1100_4__voting_procedure_indexes.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_4__voting_procedure_indexes.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_4__voting_procedure_indexes.sql
- Add logs for debugging proposal status evaluation
- Refactor WHERE clause in getVotesBySPO to use active_epoch (epoch_stake)
- Add supporting index to voting_procedure table for improved query performance
=> Add log for debugging proposal status evaluation and improve proposal status evaluation performance 

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/controller/DRepInfoController.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/ProposalDto.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/dto/SpecialDRepDto.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/service/DRepApiService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/api/governanceaggr/service/ProposalApiService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/domain/GovActionProposalStatus.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/domain/ProposalVotingStats.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/DRepStorageReader.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/DRepStorageReaderImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/GovActionProposalStatusStorageReaderImpl.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/storage/impl/model/GovActionProposalStatusEntity.java, aggregates/governance-aggr/src/main/resources/db/store/h2/V0_1400_2__add_voting_stats_column.sql, aggregates/governance-aggr/src/main/resources/db/store/mysql/V0_1400_2__add_voting_stats_column.sql, aggregates/governance-aggr/src/main/resources/db/store/postgresql/V0_1400_2__add_voting_stats_column.sql
- Add column 'voting_stats' to table 'gov_action_proposal_status" and update code accordingly
- Add endpoints for no-confidence, auto-abstain dRep info
=> Voting stats for governance action proposals

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/AdaPotConfiguration.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/AdaPotProperties.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/EpochStakePruningService.java, aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/EpochStakeService.java, docs/pages/other-configurations.mdx, starters/adapot-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/adapot/AdaPotAutoConfigProperties.java, starters/adapot-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/adapot/AdaPotAutoConfiguration.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/scheduler/TransactionPruningService.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/scheduler/UtxoPruningService.java
=> Support epoch stake pruning

.github/workflows/release.yml, build.gradle, gradle.properties, gradle/libs.versions.toml, publish-common.gradle, starters/build.gradle
- Update to CCL 0.6.6 (https://github.com/bloxbean/cardano-client-lib/pull/503)
- Yaci 0.3.6
- Change maven central URLs for new release flow.
=> Fix #575 native script parse error in preview

aggregates/governance-aggr/src/main/resources/db/store/mysql/V0_1400_1__init.sql
=> fix(mysql): update primary key of drep_dist table

components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/AutoRecoveryStartService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/processor/RequiredRestartProcessor.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/HealthService.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/internal/RequiredSyncRestartEvent.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
Merge for 0.1.5 release
https://github.com/bloxbean/yaci-store/pull/631
=> Add Auto-Restart Feature for IntersectionNotFound Errors

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java
Fixed connection reset issue when sync moves from blockfetch to chainsync.
Introduced `shutdownRangeSync` to better handle the stopping of block range sync. Enhanced keep-alive logic with additional debug logging for better traceability during sync modes. This ensures cleaner shutdown processes and improved monitoring of sync communications.
=> Fix: Connection reset issue. Shutdown unused BlockRangeSync when we move to BlockSync

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/ChainTipService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/TipFinderService.java, components/core/src/test/java/com/bloxbean/cardano/yaci/store/core/service/TipFinderServiceTest.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java
https://github.com/bloxbean/yaci-store/pull/634
=> Merge fix for connection reset issue from main branch

stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/ByronTransactionProcessor.java
=> fix:  store Byron transactions after resolving fee for unresolved fee transactions

stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/ByronTransactionProcessor.java
=> [Merge to main] Fix: store Byron transactions after resolving fee for unresolved fee transactions 
