bloxbean/yaci-store

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/model/CursorEntity.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/model/CursorId.java, components/core/src/main/resources/db/migration/h2/V0_000_1__init.sql, components/core/src/main/resources/db/migration/mysql/V0_000_1__init.sql, components/core/src/main/resources/db/migration/postgresql/V0_000_1__init.sql
For mainnet, byron block number which is a derived value is not set correctly in cursor_ table.
For block 1 is set as 0, block 2 is set as 1
Reason:
The primary key for the cursor_table is id (event_publisher_id), slot. In the mainnet, both block 0 and block 1 have the same slot number, which is 0. As a result, block 0 is being overwritten by block 1.
Fix:
Change the primary key to (id, block_hash)
@matiwinnetou, Re-sync is required after this PR.
=> fix(core) : #36 Update primary key to (id, block_hash)

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/StoreConfiguration.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/StoreProperties.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/CursorCleanupScheduler.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/api/CursorStorage.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/CursorRepository.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/storage/impl/CursorStorageImpl.java, gradle/libs.versions.toml, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
- Added scheduler to delete old cursor records in cursor_ table
**Properties:**
```
store:
cardano:
cursor-cleanup-interval: <Interval In Sec>
cursor-no-of-blocks-to-keep: <No of blocks to keep>
```
**Default Value**
```
store:
cardano:
cursor-cleanup-interval: 3600
cursor-no-of-blocks-to-keep: 2160
```
**To disable cleanup scheduler**
Set no of blocks to keep to -1
```
store:
cardano:
cursor-no-of-blocks-to-keep: -1
```
=> feat: Enable cleanup of cursor table

gradle.properties, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/helper/RedeemerDatumMatcher.java, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/helper/ScriptContext.java, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/processor/ScriptRedeemerDatumProcessor.java
#98 
- Redeemer data can be searched by redeemer datahash using the same endpoint as datum by datum hash
=> Add support to search redeemer data by data hash

applications/admin/build.gradle, applications/aggregation-app/build.gradle, applications/all/build.gradle, applications/gateway/build.gradle, applications/utxo-indexer/build.gradle, build.gradle, docs/getting-started-as-library.md, gradle/libs.versions.toml, publish-common.gradle, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/GovActionProposalEntity.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/GovActionProposalId.java, stores/governance/src/main/java/com/bloxbean/cardano/yaci/store/governance/storage/impl/model/VotingProcedureEntity.java, stores/governance/src/main/resources/db/store/h2/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql, stores/governance/src/main/resources/db/store/postgresql/V0_1100_1__init.sql, stores/governance/src/test/resources/scripts/gov_action_proposal_data.sql, stores/governance/src/test/resources/scripts/voting_procedure_data.sql, test-scripts/query.http
- Spring Boot 3.2.2 
- Driver version upgrade (mysql, postgres)
- Fix governance table data types for H2 and mysql
- Rename "index" column to "idx" for mysql as "index" is a reserve keyword in mysql
=> chore: Upgrade to spring boot 3.2.2 and sql datatype fix for H2 & mysql

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/util/JsonUtil.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/model/InvalidTransactionEntity.java
Issue #209 
- Removed NUL character (\u0000) which is not allowed in Postgres jsonb column
@Sotatek-HuyLe3a Do you know any better way to do this?
Also, should we implement this sanitization in Yaci? Currently, we need to apply this logic in 3 different places wherever the Amount field is present.
I'm not sure if it's ok to change the original string due to PostgreSQL limitations. However, we also have the `assetNameAsBytes` field, which contains the original byte array, so it might be acceptable to make this change.
=> fix: #209 Removed NUL character (\u0000) which is not allowed in Postgres jsonb column

aggregates/account/build.gradle, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreProperties.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressTxAmountProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AddressStorageImpl.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfigProperties.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfiguration.java
- Separate AddressProcessor to save addresses
- Keep cache for existing addresses to reduce no of inserts
- Currently using Guava for caching. This will be replaced with Spring Cache later.
=> chore: Maintain address cache and new AddressProcessor

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/config/AccountBatchConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/AccountConfigUpdateTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/AddressAggregationTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/job/StakeAddressAggregationTasklet.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/service/BalanceSnapshotService.java, components/job/scripts/job_reset.sql
- Added "limit" to "select address" query to avoid full scan of address_tx_amount table.
- Remove "time" from job parameter to keep 1 job instance per snapshot block
=> Fix job restart

applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/storage/DummyDBUtxoStorage.java, applications/aggregation-app/src/main/resources/sql/create-index.sql, applications/aggregation-app/src/main/resources/sql/drop-index.sql, applications/aggregation-app/src/main/resources/sql/mysql/create-index.sql, applications/aggregation-app/src/main/resources/sql/mysql/drop-index.sql, applications/all/src/main/resources/sql/create-index.sql, applications/all/src/main/resources/sql/drop-index.sql, applications/all/src/main/resources/sql/mysql/create-index.sql, applications/all/src/main/resources/sql/mysql/drop-index.sql, extensions/utxo-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/utxo/rocksdb/RocksDBUtxoStorage.java, extensions/utxo-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/utxo/rocksdb/RocksDBUtxoStorageReader.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/UtxoStoreConfiguration.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/UtxoStorage.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/UtxoStorageReader.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageImpl.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageReaderImpl.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/mapper/UtxoMapperDecorator.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/model/AddressUtxoEntity.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/model/AmountId.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/model/AmtEntity.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/repository/AmtRepository.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/repository/UtxoRepository.java, stores/utxo/src/main/resources/db/store/h2/V0_200_1__init.sql, stores/utxo/src/main/resources/db/store/mysql/V0_200_1__init.sql, stores/utxo/src/main/resources/db/store/postgresql/V0_200_1__init.sql, stores/utxo/src/test/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoRollbackProcessorIT.java, stores/utxo/src/test/resources/application.yml
Currently, the ``address_utxo`` table is used to store UTXOs, including their amounts. The ``amount`` field is a JSON field used to store a json array of amounts for the UTXO. This simplifies the saving and retrieval of UTXO in one query.
However, this creates complexity when we need to calculate the account balance based on current UTXOs. The application needs to retrieve all UTXO records for an address to the application layer and perform the aggregation in the Java layer. Also, searching by unit, policy, etc., requires a JSON query.
**Requirements:**
- Balance aggregation using utxos in db queries
- Simplify utxo search by unit, policy, asset name
**Changes**
- Create a new table utxo_amount to store UTXO amounts with the primary key tx_hash, output_index, and unit.
- Update all read …
=> chore: Create a separate table utxo_amount for utxo amounts

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreConfiguration.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreProperties.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceHistoryCleanupHelper.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AddressTxAmountProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AccountBalanceStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AccountBalanceStorageImpl.java, extensions/account-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/account/rocksdb/RocksDBAccountBalanceStorageImpl.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfigProperties.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java, stores-api/utxo-api/build.gradle, stores-api/utxo-api/src/main/java/com/bloxbean/cardano/yaci/store/api/utxo/UtxoApiConfiguration.java, stores-api/utxo-api/src/main/java/com/bloxbean/cardano/yaci/store/api/utxo/client/RetryableUtxoClient.java
- Delete balance records in batch through sql during real-time balance calculation. Currently it's done one by one.
- Introduce RetryableUtxoClient to retry in case of failure to fetch utxos. (Used in Address balance calculation and Address Tx amount processor)
- Added new properties to auto-configuration
=> Real-time balance history deletion

starters/transaction-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/transaction/TransactionAutoConfigProperties.java, starters/transaction-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/transaction/TransactionStoreAutoConfiguration.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/TransactionStoreConfiguration.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/TransactionStoreProperties.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/scheduler/TransactionPruningService.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/TransactionStorage.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/TransactionWitnessStorage.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/TransactionStorageImpl.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/TransactionWitnessStorageImpl.java
=> feat: #225 add transaction pruning service

stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageReaderImpl.java
To fix utxo by asset query for H2. 
- Added another OR condition without space between "unit:" and unit value.
=> chore: Added an or condition for H2 where there is no space

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/ProtocolParams.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/genesis/ConwayGenesis.java, components/common/src/test/java/com/bloxbean/carano/yaci/store/common/genesis/ConwayGenesisTest.java, gradle.properties, gradle/libs.versions.toml
- Change minFeeREfScriptCostPerBytes from Integer to BigDecimal
- Update Yaci (0.3.0-beta14) to fix https://github.com/bloxbean/yaci/pull/67
=> Handle pp getMinFeeRefScriptCostPerByte in 8.11.0

stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/PPEraChangeRules.java
=> fix: #299 apply previous era rules if network starts directly from Babbage or Conway era

stores/governance/src/main/resources/db/store/mysql/V0_1100_1__init.sql
- Fix mysql data type issue for gov store migration script
=> fix: Update data type to longtext to fix sql error

api-tests/epoch.http, api-tests/http-client.env.json, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/EraService.java, components/core/src/test/java/com/bloxbean/cardano/yaci/store/core/service/EraServiceTest.java, stores-api/epoch-api/src/main/java/com/bloxbean/cardano/yaci/store/api/epoch/controller/LocalEpochController.java, stores/epoch/build.gradle, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/EpochStoreConfiguration.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/processor/LocalEpochParamsScheduler.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/service/LocalEpochParamService.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/LocalEpochParamsStorage.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/LocalEpochParamsStorageImpl.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/model/LocalEpochParamsEntity.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/repository/LocalEpochParamsRepository.java, stores/epoch/src/main/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/repository/LocalProtocolParamsRepository.java, stores/epoch/src/main/resources/db/store/h2/V0_500_1__init.sql, stores/epoch/src/main/resources/db/store/mysql/V0_500_1__init.sql, stores/epoch/src/main/resources/db/store/postgresql/V0_500_1__init.sql, stores/epoch/src/test/java/com/bloxbean/cardano/yaci/store/epoch/processor/LocalEpochParamsSchedulerTest.java, stores/epoch/src/test/java/com/bloxbean/cardano/yaci/store/epoch/storage/impl/LocalEpochParamsStorageImplTest.java
- Rename local_protocol_params to local_epoch_param
- Add epoch column
- http tests for `LocalEpochController`
- Fix initial era's slot and block in Era table for custom network and preview when the chain doesn't start with Byron era. The existing value "-1" for block and slot provide wrong epoch no. Instead of -1, now the value is set to 0.
- EraService has a new method `getCurrentEpoch` to get the current epoch calculated from current tip directly from node.
=> Add "epoch" column to local_epoch_param table

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/service/AccountService.java, applications/aggregation-app/src/main/java/com/bloxbean/cardano/yaci/store/aggregation/exception/RestResponseEntityExceptionHandler.java, applications/all/src/main/java/com/bloxbean/cardano/yaci/store/app/exception/RestResponseEntityExceptionHandler.java, applications/utxo-indexer/src/main/java/com/bloxbean/cardano/yaci/store/app/utxo/exception/RestResponseEntityExceptionHandler.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/core/build.gradle, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/local/LocalClientProviderManager.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/local/LocalClientProviderPoolObjectFactory.java, config/application.properties, gradle/libs.versions.toml, starters/spring-boot-starter/build.gradle, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
To fix https://github.com/bloxbean/yaci-store/issues/341
- Added n2c pool support with Apache commons pool2
- Pool can be enabled/disabled through config
- If disabled, a new connection will be created/closed for every request
- `LocalClientProviderManager.getLocalClientProvider()` can be used to get a LocalClientProvider. If pool is enabled, it will return LocalClientProvider from the pool, otherwise a new object will be created.
- `LocalClientProviderManager.getNewLocalClientProvider()` can be used to get a new LocalClientProvider
=> feat: Pool support for N2c connections

starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoProcessor.java, stores/utxo/src/test/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoProcessorTest.java
- Fixed utxo processing for transactions without collateral return in UtxoProcessor. 
- Refactored tests to update the handling of spent and unspent UTXOs, including new test cases for scenarios with no collateral return.
- Remove default host/port/protocol magic as IOHK mainnet server are not available now
=> Refactor UtxoProcessor to handle transactions without collateral return

aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/api/account/controller/AccountController.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/util/StringUtil.java
Refactored `AccountController` to include policyId and assetName for balance units. Implemented `getPolicyIdAndAssetName` utility method and added `isValidUTF8` method in `StringUtil` for proper asset name decoding.
To fix #363
=> Add policyId and assetName extraction for balances

api-tests/address.http, extensions/utxo-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/utxo/rocksdb/RocksDBUtxoStorageReader.java, stores-api/utxo-api/src/main/java/com/bloxbean/cardano/yaci/store/api/utxo/controller/AddressController.java, stores-api/utxo-api/src/main/java/com/bloxbean/cardano/yaci/store/api/utxo/service/AddressService.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/domain/AddressTransaction.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/UtxoStorageReader.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageReaderImpl.java
- Endpoint to get transactions by address
- Change the default ordering of other endpoints to `desc` (But ordering is not currently implemented for other endpoints in the controller)
- Http tests for address endpoints
#368
=> Feat/addr Add get transactions by address endpoint

docker/application.properties, docker/yaci-store-aggregation.yml, docker/yaci-store-all.yml, docker/yaci-store-utxo-indexer.yml
Switched Cardano host to a new URL and added new governance and pool configuration settings in application.properties. Updated yaci-store Docker images to version 0.1.0-rc6 for various services.
=> Update Cardano config and Docker images to rc6

stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/processor/ScriptRedeemerDatumProcessor.java, stores/script/src/main/java/com/bloxbean/cardano/yaci/store/script/processor/ScriptRefProcessor.java
Handle exception when getting script hash in ScriptRefProcessor and ScriptRedeemerDatumProcessor
to fix #383
=> [script store] handle exception when getting script hash

gradle/libs.versions.toml
- yaci: Bumped to version 0.3.3
- cardano-client-lib: Updated to 0.6.2
- cardano-client-backend: Updated to 0.6.2
- cardano-client-backend-ogmios: Updated to 0.6.2
=> chore: bump version for yaci, cardano-client-lib, cardano-client-backend, cardano-client-backend-ogmios

api-tests/block.http, gradle/libs.versions.toml, stores-api/blocks-api/src/main/java/com/bloxbean/cardano/yaci/store/api/blocks/controller/BlockController.java, stores-api/blocks-api/src/main/java/com/bloxbean/cardano/yaci/store/api/blocks/dto/BlockDto.java
=> Blockfrost Block by number/hash api Response Format Mismatch

aggregates/adapot/src/main/java/com/bloxbean/cardano/yaci/store/adapot/service/EpochRewardCalculationService.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/domain/Txn.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/processor/TransactionProcessor.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/TransactionStorageReader.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/TransactionStorageReaderImpl.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/model/TxnEntity.java, stores/transaction/src/main/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/repository/TxnEntityRepository.java, stores/transaction/src/main/resources/db/store/h2/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/mysql/V0_300_1__init.sql, stores/transaction/src/main/resources/db/store/postgresql/V0_300_1__init.sql, stores/transaction/src/test/java/com/bloxbean/cardano/yaci/store/transaction/storage/impl/TransactionStorageReaderImplTest.java
#438 
- New "treasury_donation" column in transaction table
- Add previous epoch's donation to treasury amount during ledger state calculation
=> feat: #438 store donation in transaction table. Add donation to the treasury amount during ledger state calculation.

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/TreasuryWithdrawalProcessor.java, aggregates/governance-aggr/src/test/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/TreasuryWithdrawalProcessorTest.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/domain/RewardRestType.java
- Store the reward in the 'reward_rest' table, where the earned_epoch is the ratified epoch, and the spendable epoch is the earned_epoch plus 1 (the enacted epoch). The reward type is 'treasury'.
- Verified with yaci-devkit: The effect of this reward type on epoch stake is similar to that of the proposal refund.
=> feat: #449 store reward from treasury withdrawal action

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/GovernanceAggrProperties.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-rules/src/main/java/com/bloxbean/cardano/yaci/store/governancerules/rule/CommitteeVotingState.java, aggregates/governance-rules/src/main/java/com/bloxbean/cardano/yaci/store/governancerules/rule/DRepVotingState.java, aggregates/governance-rules/src/main/java/com/bloxbean/cardano/yaci/store/governancerules/rule/GovActionRatifier.java, aggregates/governance-rules/src/main/java/com/bloxbean/cardano/yaci/store/governancerules/rule/SPOVotingState.java, config/application-ledger-state.properties, starters/governance-aggr-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/governanceaggr/GovernanceAggrAutoConfigProperties.java, starters/governance-aggr-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/governanceaggr/GovernanceAggrStoreAutoConfiguration.java
- In governance-rule, use DRep info instead of SPO info when the action is treasury withdrawal.
- In governance-rule, check for null in DRepVotingState, SPOVotingState, CommiteeVotingState
- In class ProposalStatusProcessor:
- Rename isBootstrapPhase -> isInConwayBootstrapPhase
- When retrieving the treasury value (The value helps us check whether a withdrawal is possible), use current epoch (the epoch at the time we calculate gov action status)
- Rename GovernanceAggrStoreAutoConfigProperties -> GovernanceAggrAutoConfigProperties
- Add property to check Conway bootstrap is available in devnet network
=> Fix: treasury withdrawal ratification not working as expected with DevKit node 

gradle.properties, gradle/libs.versions.toml
- Update Yaci to version 0.3.5, which includes the proper fix for the redeemer parsing error. The previous version, 0.3.4.1, only implemented a workaround.
=> Update to Yaci 0.3.5

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/genesis/ByronGenesis.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/configuration/GenesisConfig.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/EraService.java
Introduced `byronEpochLength` to handle epoch length specific to the Byron era. Adjusted slot duration calculations in `EraService` to use `Math.round` for better precision. These changes ensure accurate timeline calculations across different eras and slot length below 1 second.
=> Add Byron epoch length support and fix slot duration calculations

aggregates/account/build.gradle, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/AccountStoreProperties.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/domain/BalanceRollbackEvent.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/processor/AccountBalanceRollbackProcessor.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/AccountBalanceStorage.java, aggregates/account/src/main/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AccountBalanceStorageImpl.java, aggregates/account/src/main/resources/META-INF/native-image/yaci-store-account/reflect-config.json, aggregates/account/src/main/resources/db/store/h2/V0_900_6__current_tables.sql, aggregates/account/src/main/resources/db/store/mysql/V0_900_6__current_tables.sql, aggregates/account/src/main/resources/db/store/postgresql/V0_900_6__current_tables.sql, aggregates/account/src/test/java/com/bloxbean/cardano/yaci/store/account/config/JooqTestConfig.java, aggregates/account/src/test/java/com/bloxbean/cardano/yaci/store/account/storage/impl/AccountBalanceStorageImplTest.java, aggregates/account/src/test/resources/application.properties, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/StartService.java, components/events/src/main/java/com/bloxbean/cardano/yaci/store/events/PreRollbackEvent.java, extensions/account-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/account/rocksdb/RocksDBAccountBalanceStorageImpl.java, extensions/utxo-rocksdb/src/main/java/com/bloxbean/cardano/yaci/store/extensions/utxo/rocksdb/RocksDBUtxoStorage.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfigProperties.java, starters/account-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/account/AccountStoreAutoConfiguration.java, starters/utxo-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/utxo/UtxoStoreAutoConfigProperties.java, starters/utxo-spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/utxo/UtxoStoreAutoConfiguration.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/UtxoStoreProperties.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/domain/UtxoRollbackEvent.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/processor/UtxoRollbackProcessor.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/UtxoStorage.java, stores/utxo/src/main/java/com/bloxbean/cardano/yaci/store/utxo/storage/impl/UtxoStorageImpl.java
This PR introduces the following new features:
1. **Content-Aware Rollback Events**
2. **Pre-Rollback Event**
3. **Current Balance Tables for `address_balance` and `stake_address_balance`**
---
Currently, our rollback strategy is based solely on the `slot` value. This works well for most tables, which are append-only and include a `slot` column.
However, this approach can cause issues for applications that maintain derived values using in-place updates.
To address this, we are introducing a new optional event type that informs applications of the specific data (e.g., addresses, UTxOs) that will be rolled back—*before* the rollback is applied.
This enables applications to adjust derived values or perform cleanup based on rollback impact.
* `UtxoRollbackEvent` in the UTXO store
* …
=> Introduce Content-Aware Rollback Events, Pre-Rollback Event, and Current Balance Tracking

components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/variables/NamedBeansVariableProvider.java
This PR exposes storage readers as binding variables, allowing plugins to read data from the database.
=> Expose storage readers as binding variables for plugins

docker/grafana/dashboards/yaci-store-dashboard.json
Introduced panels for System Uptime, JVM Memory Usage, CPU Usage, Database Connection Pool, and HTTP performance metrics in the Yaci Store dashboard. Updated layouts, colors, units, and added legends for better clarity and precision. 
@matiwinnetou fyi.
=> Add new panels and rows for enhanced monitoring in Grafana

components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/variables/DefaultVariableProvider.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/variables/NamedBeansVariableProvider.java
- Modified DefaultVariableProvider to cache the variable map in the constructor to avoid repeated object creation during sync.
- Updated NamedBeansVariableProvider to use lazy initialization.
=> Optimize VariableProvider implementations by caching variable maps

docs/pages/ledger-state-mismatches/2-0-0-beta1/_meta.json, docs/pages/ledger-state-mismatches/2-0-0-beta3/2-0-0-beta3.mdx, docs/pages/ledger-state-mismatches/2-0-0-beta3/_meta.json, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/_hidden/drep-distribution-analysis.mdx, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/_hidden/drep-distribution-summary.mdx, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/_meta.json, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/drep-active-until-detail.mdx, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/drep-distribution-detail.mdx, docs/pages/ledger-state-mismatches/2-0-0-beta3/mainnet/drep-distribution/_meta.json, docs/pages/ledger-state-mismatches/_meta.json
Simplified the Ledger State Mismatches section.
-  Removed the summary and detailed analysis from DRep Distribution.
-  Moved the sub-menu under "DRep Active Until" since it only has one page. Now there are just two direct pages under "Mainnet"
=> chore(ledger-state-mismatches): update menu structure and simplify content

components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/api/AdminController.java, components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/AutoRecoveryStartService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/HealthStatus.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/metrics/MetricsService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/HealthService.java, config/application.properties, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
#621 
3 new metrics:
- `yaci.store.connection.status`  : connection status (1: up, 0: down)
- `yaci.store.last_received_block_time` :Timestamp of the last received block in milliseconds
- `yaci.store.current.slot`: current slot being processed
Improvements:
- Enhance HealthService  by providing additional isReceivingBlocks status for enhanced monitoring
=> chore: add metrics tracking for connection status and resets

.github/workflows/build.yml, gradle.properties, gradle/libs.versions.toml
Bump project version to 0.1.5-beta and upgrade YACI library to 0.3.8. These changes ensure compatibility with the latest updates and prepare for a beta release.
=> Update version and Yaci library

components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/metrics/MetricsService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, config/application.properties, docker/application.properties
Removed the connection status metric to avoid confusion, and updated the host and port for the preview and preprod public nodes.
=> Fix: remove connection status metric and update new Cardano node host, port

components/admin/src/main/java/com/bloxbean/cardano/yaci/store/admin/service/AutoRecoveryStartService.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/domain/HealthStatus.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/metrics/MetricsService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/BlockFetchService.java, components/core/src/main/java/com/bloxbean/cardano/yaci/store/core/service/HealthService.java, config/application.properties, gradle/libs.versions.toml, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
- Merge the changes in https://github.com/bloxbean/yaci-store/pull/630 to main
- Upgrade yaci library to 0.4.0-beta5
- Fix: Connection reset issue. Shutdown unused BlockRangeSync when we move to BlockSync. Check detail: https://github.com/bloxbean/yaci-store/pull/638
- Fix: remove connection status metric and update new Cardano node host, port. Check detail: https://github.com/bloxbean/yaci-store/pull/639
- Refactor sync stopping logic to handle null checks and exceptions. Check : https://github.com/bloxbean/yaci-store/pull/640
=> Feat/merge connection metrics and update restart condition, shutdown unused BlockRangeSync when we move to BlockSync

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalRefundProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DRepDistService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/VotingAggrService.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/util/ProposalUtils.java, aggregates/governance-aggr/src/test/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalRefundProcessorTest.java
This pull request aims to fix issues related to the calculation of DRep distribution and proposal dropping logic.
- Updated the logic for dropping proposals: if a proposal is ratified, its sibling proposals and the descendants of those siblings will be dropped. 
- Added a temporary table `ss_gov_scheduled_to_drop_proposal_deposits` to store deposits of proposals scheduled to be dropped. These deposit values will be subtracted when calculating DRep voting power.
- **Purpose groups**: Proposals are grouped by purpose (PParamUpdatePurpose, HardForkPurpose, CommitteePurpose, ConstitutionPurpose)
- **Sibling identification**: Proposals with the same purpose and same parent are considered siblings
- **Dropping rules**: When a proposal is ratified, all its siblings and descendants of those …
=> Fix: Correct proposal dropping logic for ratified/expired proposals

docker/compose/yaci-store.yml, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
Modified the default `rootPath` in `YaciStoreProperties` to align with the updated folder structure. Additionally, added a volume mapping in the Docker Compose file for the `plugins/files` directory to ensure proper file handling.
=> Update file path configuration and Docker volume mapping

components/common/src/main/java/com/bloxbean/cardano/yaci/store/common/config/StoreProperties.java, components/plugin-api/src/main/java/com/bloxbean/cardano/yaci/store/plugin/api/PluginFactory.java, components/plugin-api/src/main/java/com/bloxbean/cardano/yaci/store/plugin/api/PluginType.java, components/plugin-api/src/main/java/com/bloxbean/cardano/yaci/store/plugin/api/SchedulerPlugin.java, components/plugin-api/src/main/java/com/bloxbean/cardano/yaci/store/plugin/api/config/SchedulerPluginDef.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/common/GraalPolyglotScriptStorePlugin.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/common/PolyglotConverter.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/common/Unwrapper.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/common/ValueConverter.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/js/JsPolyglotPluginFactory.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/js/JsScriptStorePlugin.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/python/PythonPolyglotPluginFactory.java, components/plugin-polyglot/src/main/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/python/PythonScriptStorePlugin.java, components/plugin-polyglot/src/test/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/js/JsSchedulerPluginIntegrationTest.java, components/plugin-polyglot/src/test/java/com/bloxbean/cardano/yaci/store/plugin/polyglot/python/PythonSchedulerPluginIntegrationTest.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/core/PluginRegistry.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/impl/mvel/MvelScriptStorePlugin.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/impl/mvel/MvelStorePluginFactory.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/impl/spel/SpelStorePluginFactory.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/scheduler/SchedulerConfiguration.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/scheduler/SchedulerService.java, components/plugin/src/main/java/com/bloxbean/cardano/yaci/store/plugin/scheduler/SchedulerVariableContext.java, components/plugin/src/test/java/com/bloxbean/cardano/yaci/store/plugin/impl/mvel/MvelSchedulerPluginBasicTest.java, components/plugin/src/test/java/com/bloxbean/cardano/yaci/store/plugin/impl/mvel/MvelSchedulerPluginTest.java, components/plugin/src/test/java/com/bloxbean/cardano/yaci/store/plugin/scheduler/SchedulerServiceIntegrationTest.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreAutoConfiguration.java, starters/spring-boot-starter/src/main/java/com/bloxbean/cardano/yaci/store/starter/core/YaciStoreProperties.java
- Add SchedulerPlugin interface and SchedulerPluginDef configuration
- Implement SchedulerService with Spring TaskScheduler integration
- Add scheduler variable context for runtime variable injection
- Support interval-based scheduling with configurable error handling
- Extend plugin factories (MVEL, SpEL, JavaScript, Python) with scheduler support
- Add polyglot converter utilities for complex object handling in scripts
- Add comprehensive integration tests for all plugin types
- Configure scheduler in Spring Boot starter with conditional loading
**Example:**
```
store:
plugins:
enabled: true
schedulers:
- name: "metrics-logger"
lang: "mvel"
schedule:
type: "INTERVAL"
value: "60"  # Execute every 60 seconds
inlineScript: |
// Log metrics every minute
executionNum = …
```
=> feat: #622 Add scheduler plugin support with interval-based scheduling

aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/processor/ProposalStatusProcessor.java, aggregates/governance-aggr/src/main/java/com/bloxbean/cardano/yaci/store/governanceaggr/service/DelegationVoteDataService.java
- Fixed a bug in ProposalStatusProcessor where committee members were incorrectly identified as non-voters due to missing proposal-specific filtering.
- Fixed bug related to the calculation of total stake delegated by SPOs to the AlwaysAbstain DRep
- Added proposal filtering (txHash + index) before checking which committee members didn't vote
- Fixed query for fetching delegation votes by drep type and address list
- Refactored stake calculation for delegations by SPOs to the AlwaysAbstain and NoConfidence DReps to ensure thread-safety
- Calculated the total stake delegated by SPOs to the AlwaysAbstain and NoConfidence DReps in batches
=> Fix committee non-voter identification in proposal status calculation & Fix calculation of total stake delegated by SPOs to the AlwaysAbstain DRep
